CREATE TABLE IF NOT EXISTS coffee_purchases (id INTEGER PRIMARY KEY AUTOINCREMENT, date TEXT NOT NULL, location TEXT NOT NULL, payer TEXT NOT NULL, present_members TEXT NOT NULL);
INSERT INTO coffee_purchases (id,date,location,payer,present_members) VALUES (1,'2026-03-10','Bunbury','Bill','["Bill", "Dom", "Jim"]');
INSERT INTO coffee_purchases (id,date,location,payer,present_members) VALUES (2,'2026-03-11','Bunbury','Tony','["Bill", "Tony"]');
INSERT INTO coffee_purchases (id,date,location,payer,present_members) VALUES (3,'2026-03-29','Dottie A','Bill','["Bill", "Tony"]');
INSERT INTO coffee_purchases (id,date,location,payer,present_members) VALUES (4,'2026-03-31','Bunbury','Jim','["Bill", "Dom", "Jim"]');
INSERT INTO coffee_purchases (id,date,location,payer,present_members) VALUES (5,'2026-04-15','Bunbury','Bill','["Bill", "Dom", "Jim", "Tony"]');
INSERT INTO coffee_purchases (id,date,location,payer,present_members) VALUES (6,'2026-04-17','Bunbury','Dom','["Dom", "Tony", "Bill"]');
INSERT INTO coffee_purchases (id,date,location,payer,present_members) VALUES (7,'2026-04-29','Other','Bill','["Bill", "Dom", "Jim", "Tony"]');
INSERT INTO coffee_purchases (id,date,location,payer,present_members) VALUES (9,'2026-05-01','Dottie A','Dom','["Bill", "Dom", "Jim"]');
INSERT INTO coffee_purchases (id,date,location,payer,present_members) VALUES (8,'2026-05-06','Bunbury','Bill','["Bill", "Dom", "Tony"]');
INSERT INTO coffee_purchases (id,date,location,payer,present_members) VALUES (10,'2026-05-15','Bunbury','Tony','["Bill", "Dom", "Jim", "Tommy"]');
INSERT INTO coffee_purchases (id,date,location,payer,present_members) VALUES (11,'2026-05-29','Bunbury','Dom','["Bill", "Dom", "Jim"]');
INSERT INTO coffee_purchases (id,date,location,payer,present_members) VALUES (12,'2026-06-24','Bunbury','Bill','["Bill", "Dom", "Jim"]');
INSERT INTO coffee_purchases (id,date,location,payer,present_members) VALUES (13,'2026-06-30','Bunbury','Dom','["Bill", "Dom", "Jim"]');
INSERT INTO coffee_purchases (id,date,location,payer,present_members) VALUES (16,'2026-07-10','Bunbury','Jim','["Bill", "Jim"]');
INSERT INTO coffee_purchases (id,date,location,payer,present_members) VALUES (15,'2026-07-14','Other','Bill','["Bill", "Dom"]');
INSERT INTO coffee_purchases (id,date,location,payer,present_members) VALUES (14,'2026-07-15','Bunbury','Dom','["Bill", "Dom", "Jim"]');
INSERT INTO coffee_purchases (id,date,location,payer,present_members) VALUES (17,'2026-07-18','Bunbury','Tony','["Bill", "Dom", "Jim", "Tony"]');
INSERT INTO coffee_purchases (id,date,location,payer,present_members) VALUES (18,'2026-08-05','Bunbury','Bill','["Bill", "Dom", "Jim", "Tony"]');
INSERT INTO coffee_purchases (id,date,location,payer,present_members) VALUES (19,'2026-08-08','Bunbury','Tony','["Bill", "Tony"]');
INSERT INTO coffee_purchases (id,date,location,payer,present_members) VALUES (20,'2026-08-26','Bunbury','Dom','["Bill", "Dom", "Tony"]');
INSERT INTO coffee_purchases (id,date,location,payer,present_members) VALUES (21,'2026-09-05','Other','Bill','["Bill", "Tony"]');
INSERT INTO coffee_purchases (id,date,location,payer,present_members) VALUES (22,'2026-10-03','Other','Bill','["Bill", "Jim"]');
INSERT INTO coffee_purchases (id,date,location,payer,present_members) VALUES (23,'2026-10-06','Other','Tony','["Jim", "Tony"]');
INSERT INTO coffee_purchases (id,date,location,payer,present_members) VALUES (24,'2026-10-08','Bunbury','Dom','["Bill", "Dom", "Jim"]');
